---

# First 
#- name: Adding Beegfs repo
#  tags: beegfs
#  yum_repository:
#    name: BeeGFS 6 (RHEL7)
#    description: BeeGFS http://www.beegfs.io/ rpm release
#    #baseurl: file:///home/Mellanox-repo/RPMS
#    baseurl: "http://www.beegfs.io/release/beegfs_6/dists/rhel{{ ansible_distribution_major_version }}"
#    gpgkey: "http://www.beegfs.io/release/beegfs_6/gpg/RPM-GPG-KEY-beegfs"
#    gpgcheck: no
#  when: ansible_os_family == 'RedHat'

#- name: initialize BeeGFS-client
#  tags: beegfs-client
#  shell: /opt/beegfs/sbin/beegfs-setup-client -m "{{ beegfs_server }}"

- name: copy over net.conf selecting used interfaces
  tags: beegfs-client
  template: src="net.conf" dest="/etc/beegfs/net.conf"

- name: Make sure that mount-directory exists
  tags: beegfs-client
  file: path={{ item.name }} state=directory owner=root group=root mode=0775
  with_items: "{{ beegfs_mounts | default({}) }}"

- name: copy over beegfs-mounts.conf listing mounts
  tags: beegfs-client
  template: src="beegfs-mounts.conf" dest="/etc/beegfs/beegfs-mounts.conf"

- name: copy over beegfs-client.conf:ikset 
  copy: src="files/beegfs-client.conf" dest="{{ item.src }}"
  with_items: "{{ beegfs_mounts | default({}) }}"
  notify: restart beegfs-client
